### ISSUE TITLE
[Documentation] [Install] [Ubuntu 22.04] Command apt-key is deprecated and has warnings about that.

### ISSUE THREAD

**Issue by jmwielandt** [rethinkdb/docs#1319]
After a few tries, I manage to install RethinkDB in Ubuntu 22.04 LTS (wsl2 on windows 10). 

This are the new commands:

```bash
# download public key
curl -fsSL https://download.rethinkdb.com/repository/raw/pubkey.gpg | sudo gpg --dearmor -o /usr/share/keyrings/rethinkdb-archive-keyrings.gpg

# add the repository
echo "deb [signed-by=/usr/share/keyrings/rethinkdb-archive-keyrings.gpg] https://download.rethinkdb.com/repository/ubuntu-$(lsb_release -cs) $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list

sudo apt update
sudo apt install rethinkdb

# check instalation
rethinkdb --version  # rethinkdb 2.4.2~0jammy (GCC 11.2.0)
```

This was strongly based on [redis' documentation](https://redis.io/docs/getting-started/installation/install-redis-on-linux/#install-on-ubuntu).
Please, update your [install documentation](https://rethinkdb.com/docs/install/ubuntu/) to this.

Greetings~

**Comment by srh** [comment]
Note that I moved the issue to the rethinkdb/docs repo.

With #1320 and (sigh) #1321 the issue is fixed.

The website is updated with #1320's change already, it should have #1321 in a few minutes.  Thank you!

**Comment by dotnetCarpenter** [comment]
@srh This is still an issue. https://github.com/rethinkdb/www/issues/339

Also I would do `wget -qO- https://download.rethinkdb.com/repository/raw/pubkey.gpg | sudo tee /etc/apt/trusted.gpg.d/rethinkdb.asc` instead of 0bf0d91a102b014fb58dbf93987bb7607b983d4c:

```
# Download the public key.
wget -qO- https://download.rethinkdb.com/repository/raw/pubkey.gpg | \
    sudo gpg --dearmor -o /usr/share/keyrings/rethinkdb-archive-keyrings.gpg
```

But also I have not tried `gpg --dearmor` since it is not on the [install on Debian page](https://rethinkdb.com/docs/install/debian/).
